name: ghp_society_management
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.19+20

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.0.15
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  bottom_navy_bar: ^6.1.0
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  searchbar_animation: ^0.0.4
  intl: ^0.20.2
  syncfusion_flutter_pdfviewer: ^28.2.12
  #  file_picker: ^9.0.0
  image_cropper: ^9.0.0
  flutter_file_dialog: ^3.0.2
  path_provider: ^2.1.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  share_plus: ^10.0.0
  flutter_polls: ^0.1.6
  #  video_thumbnail: ^0.5.3
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  textfield_search: ^0.11.1
  simple_ripple_animation: ^0.1.0
  vibration: ^3.1.3
  flutter_ringtone_player: ^4.0.0+3
  flutter_local_notifications: ^19.0.0
  circular_countdown_timer: ^0.2.3
  rxdart: ^0.28.0
  geolocator: ^13.0.3
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0
  #  flutter_document_picker: ^5.2.3
  flutter_html: ^3.0.0
  firebase_core: ^3.10.1
  #  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.2.4
  file_picker: ^10.1.2
  flutter_staggered_grid_view: ^0.7.0
  mobile_scanner: ^6.0.10
  marquee: ^2.3.0
  cloud_firestore: ^5.6.6
  webview_flutter: ^4.13.0
  shimmer: ^3.0.0
  video_compress: ^3.1.4
  image: ^4.5.4
  firebase_storage: ^12.4.10
  sms_autofill: ^2.4.1
  firebase_auth: ^5.7.0
  showcaseview: ^4.0.1
  flutter_sound: ^9.28.0
  carousel_slider: ^5.1.1
  pdf: ^3.11.3
  printing: ^5.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/icons/




