// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8MTQBpyTWtT7wiw7t-P4qvRZsQsjhk0',
    appId: '1:722059750239:web:723578fe8bae973ceca4ea',
    messagingSenderId: '722059750239',
    projectId: 'ghpsocietyapp-64319',
    authDomain: 'ghpsocietyapp-64319.firebaseapp.com',
    storageBucket: 'ghpsocietyapp-64319.firebasestorage.app',
    measurementId: 'G-9G1K25YRK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfw9RO0bf4YvvrhrFAGpFGnDCt-kbNPI0',
    appId: '1:722059750239:android:44fb32e09cbad6edeca4ea',
    messagingSenderId: '722059750239',
    projectId: 'ghpsocietyapp-64319',
    storageBucket: 'ghpsocietyapp-64319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUE7l564Ph6zZBNKkEQMGQfbd_1oGAwiY',
    appId: '1:722059750239:ios:10cf19b709cf9c3deca4ea',
    messagingSenderId: '722059750239',
    projectId: 'ghpsocietyapp-64319',
    storageBucket: 'ghpsocietyapp-64319.firebasestorage.app',
    iosBundleId: 'com.fp.ghpsocietyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUE7l564Ph6zZBNKkEQMGQfbd_1oGAwiY',
    appId: '1:722059750239:ios:10cf19b709cf9c3deca4ea',
    messagingSenderId: '722059750239',
    projectId: 'ghpsocietyapp-64319',
    storageBucket: 'ghpsocietyapp-64319.firebasestorage.app',
    iosBundleId: 'com.fp.ghpsocietyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY8MTQBpyTWtT7wiw7t-P4qvRZsQsjhk0',
    appId: '1:722059750239:web:8259b02d3b72833beca4ea',
    messagingSenderId: '722059750239',
    projectId: 'ghpsocietyapp-64319',
    authDomain: 'ghpsocietyapp-64319.firebaseapp.com',
    storageBucket: 'ghpsocietyapp-64319.firebasestorage.app',
    measurementId: 'G-VFD3WB88GZ',
  );
}
